# Generated by Django 5.2.10 on 2026-02-03 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='department_old',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='is_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='myapp.company')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='myapp.department'),
        ),
        migrations.AddField(
            model_name='project',
            name='departments',
            field=models.ManyToManyField(related_name='projects', to='myapp.department'),
        ),
    ]
